name: Validate PR title and labels

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  validate_pull_request:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        run: |
          # Check if PR title starts with "SDS-"
          if ! echo "${{ github.event.pull_request.title }}" | grep -qE '^SDS-[0-9]{4,5} '; then
            echo "Error: Pull request title must start with 'SDS-<JIRA ID> '"
            exit 1
          fi

      - name: Validate PR labels
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)

          # Check if "do not merge" label is present
          PULL_REQUEST_LABELS=$(cat <<$EOF
          ${{ toJson(github.event.pull_request.labels) }}
          $EOF)

          echo "1: "
          echo "$PULL_REQUEST_LABELS"
          echo "2: "
          echo $PULL_REQUEST_LABELS
          if echo $PULL_REQUEST_LABELS | jq -r '.[].name' | grep -qE 'do not merge'; then
            echo "Error: Pull request has 'do not merge' label"
            exit 1
          fi